# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Setup permissions for react-native-permissions
require_relative '../node_modules/react-native-permissions/scripts/setup'
setup_permissions([
  'Camera',
  'FaceID',
  'LocationWhenInUse', 
  'Microphone',
  'PhotoLibrary',
  'PhotoLibraryAddOnly'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'hrms' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
    )

    # Fix simulator builds on Apple Silicon
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Ensure ARCHS is not empty to prevent unbound variable error
        if config.build_settings['ARCHS'].nil? || config.build_settings['ARCHS'].empty?
          config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
        end

        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
